### ISSUE TITLE
Add enable/disable joystick button

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#517]
The Sutter stages all come with joysticks that move the stage independently of our software. This currently forces a user to press the STOP stage button to alert our program to the new stage positions prior to moving the stage from within our program. This can be annoying. Instead, I propose we have a "Activate Joystick" that disables software control of the stage when selected and returns software control to the stage when de-selected. On de-selection, we should make a forced call for the new position from the stage.

**Comment by AdvancedImagingUTSW** [comment]
![image](https://github.com/TheDeanLab/ASLM/assets/42547789/3e70c9fb-5fff-4146-b1b3-61212908d2f9)
Place on the stage control window, provide a hot key (CTRL + j) for toggling the joystick control.

When joystick is enabled, tkinter elements for controlling those stages should be disabled/inactive. 

Will have to define which stages are joystickable in stage configuration, and also the experiment file so that whatever the microscope was left at, it reboots to.
